### ISSUE TITLE
Create an api to provision sampling keys

### ISSUE THREAD

**Issue by adriancole** [openzipkin-contrib/zipkin-secondary-sampling#10]
Right now, sampling keys are provisioned externally. The only apis that exist right now are to evaluate participation in (sample) a key provided upstream. I'm creating this issue so that comments around provisioning can be centralized as opposed to tacked onto ancillary other changes.

**Comment by adriancole** [comment]
From nara about a use case for provisioning keys. the TL;DR; is that the provisioning should not be limited to only at the first request (gateway in our example app). That provisioning of keys should be possible anywhere.

This is another implicit shared understanding: that provisioning of keys may occur on the same node as they are evaluated, but are not required to be created at the node they are evaluated (ex gateway can make a key reading data it can see, but for triggering downstream where a node may not have visibility to the same data).


Here's an example workaround while there's no provisioning api. It is to make a filter that executes prior to the secondary sampling invocation.

From @narayaruna:

---

To workaround this, a servlet filter/grpc interceptor is what I am using to provision the `sampling_key`. Here is a grpc interceptor example:

```
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
            ServerCall<ReqT, RespT> call,
            Metadata requestHeaders,
            ServerCallHandler<ReqT, RespT> next
    ) {
        .....
        // apply the rules and run the sampler. If there is a match and the sampler decision is true
        // then provision the `sampling_key` 
        String samplingKey = ....
        requestHeaders.put(SAMPLING, samplingKey);

        return next.startCall(call, requestHeaders);
    }

```

**Why is this relevant?**
This is useful to provision the `sampling_key` not just in the `gateway` service but in any service downstream. For example, an `auth` service downstream can provision the `sampling_key` to start tracing 50% of calls to the `doAuth` method and the next hop by setting `ttl=2`.

**Comment by narayaruna** [comment]
@adriancole sample rules
```json
{
    "configName": "cfg1",
    "matcherSettings": {
      "methodName": "SayHello"
    },
    "samplerSettings": {
      "probability": "1.0"
    },
    "samplingInitState": {
      "label": "sayHello100pct",
      "ttl": "2"
    }
  }
```
