### ISSUE TITLE
Setup (non-jitpack) publishing

### ISSUE THREAD

**Issue by narayaruna** [openzipkin-contrib/zipkin-secondary-sampling#22]
https://github.com/openzipkin-contrib/zipkin-secondary-sampling/blob/master/pom.xml#L20

^^ need to update group id to `io.zipkin...`?

Also when can we switch to publishing the snapshot builds to standard repos jfrog and bintray.

**Comment by adriancole** [comment]
if you feel the apis so far do the minimum you need, then yeah it is probably time to consider publishing. cc @jeqo

**Comment by adriancole** [comment]
I think we still have apis to change. BTW I'm not sure if you know this but jitpack also accepts a commit has. If you ever get into trouble, you can literally paste the hash as the maven version.

**Comment by adriancole** [comment]
with the above workaround mentioned, please note I do not have time to setup publishing right now. Also there is more to it, like adding readme etc. if anyone has time to contribute to issue cleanup or polish please do!

**Comment by adriancole** [comment]
I will add some checklist here as there are a number of workflow steps.

**Comment by adriancole** [comment]
snapshots are setup. doing a test publish of 0.1.0 with the tag release-0.1.0

**Comment by adriancole** [comment]
restarted the canceled job https://travis-ci.org/openzipkin-contrib/zipkin-secondary-sampling/builds/601184479

**Comment by adriancole** [comment]
wrong upload url, re-cut tags

**Comment by adriancole** [comment]
submitted request to bintray to host https://bintray.com/openzipkin-contrib/maven/zipkin-secondary-sampling on jcenter (this is for maven group ID io.zipkin.contrib.zipkin-secondary-sampling, which will then be allowed to sync to maven central)

**Comment by adriancole** [comment]
@narayaruna can you verify you can use maven central (maybe 2hrs from now?)

While you don't need to have bintray or sonatype access to perform releases (as my credentials are saved), it is nice to have this access in case something goes wrong you can troubleshoot or restore deployment. Meanwhile, I'll close this out as everything is setup I think.
