### ISSUE TITLE
Master branch is incompatible with brave/master

### ISSUE THREAD

**Issue by narayaruna** [openzipkin-contrib/zipkin-secondary-sampling#23]
Please merge `rpc-sampling` to bring it in sync with `brave/master`.

**Comment by narayaruna** [comment]
[build-error.txt](https://github.com/openzipkin-contrib/zipkin-secondary-sampling/files/3683450/build-error.txt)

**Comment by adriancole** [comment]
was waiting for 5.8 release.. should be synced
