### ISSUE TITLE
Required java version

### ISSUE THREAD

**Issue by narayaruna** [openzipkin-contrib/zipkin-secondary-sampling#3]
Noticed Jdk 8 won't build this.

https://github.com/openzipkin-contrib/zipkin-secondary-sampling/blob/master/pom.xml#L287

**Comment by adriancole** [comment]
Do you need to build with JDK 1.8? This is decoupled from what the generated bytecode is. For example, brave is also built with JDK 11, yet runs on JRE 1.6.

**Comment by narayaruna** [comment]
I don't need to. We can keep this consistent with Brave. I was trying to deploy to maven local. I can adjust my jdk used.

**Comment by adriancole** [comment]
Cool thanks! yeah right now, we've effectively shifted to JDK 11 (considering JDK 13 is just out!)
The only projects we pin to 1.8 are those that don't run otherwise. For example, we can't budge the JDK in zipkin-dependencies as spark's unit tests won't run in anything but JDK 1.8
