### ISSUE TITLE
ttl or depth?

### ISSUE THREAD

**Issue by narayaruna** [openzipkin-contrib/zipkin-secondary-sampling#4]
https://github.com/openzipkin-contrib/zipkin-secondary-sampling/blob/d6d6c67811f40466c716804373da451455fe6fe9/brave/src/main/java/brave/secondary_sampling/SecondarySamplingPolicy.java#L23

In a discussion I got a feedback (from @kevin-lew) that ttl implies some timer involved. I went back and reviewed the initial approach document and found I have used the name `depth` for this.

Is `depth` ok or should this be renamed to something different to communicate the intent?

**Comment by adriancole** [comment]
hmm I'd argue that ttl is not like that. In fact it was taken from w3c discussion. At least there, there was no ambiguity as it is common in network programming for TTL to be hop count.

**Comment by adriancole** [comment]
In ipv6 they renamed TTL to hop limit, I'd rather use that vs making up a new term.. WDYT? https://en.wikipedia.org/wiki/Time_to_live

cc also @openzipkin-contrib/core as I'd like to avoid jargon that is unfamiliar and formerly I thought TTL was familiar.

**Comment by adriancole** [comment]
when thinking about this, it can be helpful to use examples.. ex keep in mind it will literally be encoded like this..

```
at hop 1: incident496;ttl=3
at hop 2: incident496;ttl=2
```

vs
```
at hop 1: incident496;depth=3
at hop 2: incident496;depth=2
```

vs
```
at hop 1: incident496;hopLimit=3
at hop 2: incident496;hopLimit=2
```

As you'll notice.. while in transit, the word `depth` could be confusing I think.

**Comment by narayaruna** [comment]
` TTL may be implemented as a counter or timestamp attached to or embedded in the data.`

Yeah `depth` is clear as input value but not very as an output value. 

Let's keep as is then. I now have a reference in literature to point to :)

**Comment by adriancole** [comment]
Feel free to raise other design questions, this is one great thing about having a separate repo.
