### ISSUE TITLE
`serviceName` need not be in the callback

### ISSUE THREAD

**Issue by narayaruna** [openzipkin-contrib/zipkin-secondary-sampling#5]
https://github.com/openzipkin-contrib/zipkin-secondary-sampling/blob/master/brave/src/main/java/brave/secondary_sampling/SecondarySamplingPolicy.java#L26

The `serviceName` need not be in the callback because it can be read from Spring config.

**Comment by adriancole** [comment]
good idea https://github.com/openzipkin-contrib/zipkin-secondary-sampling/pull/6
