### ISSUE TITLE
Track convenience of making secondary sampling with both grpc and http

### ISSUE THREAD

**Issue by adriancole** [openzipkin-contrib/zipkin-secondary-sampling#8]
From @narayaruna

Like how secondary sampling can be started by matching a grpc method name or a http endpoint, should it be possible to do the same for B3 sampling also? Which means a http request/grpc call should be matched in one place and rule applied for both b3 sampling or secondary sampling?

> For example, imagine the following sampling policies config to start a trace;

```
[
  {
    "configName": "cfg1",
    "samplingInitState": {
      "label": "sayHello100pct"
    },
    "matcherSettings": {
      "methodName": "SayHello"
    },
    "samplerSettings": {
      "probability": "1.0"
    }
  },
  {
    "configName": "cfg2",
    "samplingInitState": {
      "label": "sayHello10rpsWithTtl",
      "ttl": "2"
    },
    "matcherSettings": {
      "methodName": "SayHello"
    },
    "samplerSettings": {
      "rps": "10"
    }
  }
]
```

Setting this on a HelloService to enable the following sampling;

    Start a secondary sampling to trace 100% of SayHello grpc method
    Start a secondary sampling to trace 10 req/s of the SayHello grpc method for 2 hops

This means should SecondarySamplingState used for only matching service participation and updating ttl but not starting a new trace?

High level ask is, should starting a trace by setting b3 or sampling_key done in the one place so applying the matching rule can be done in one place.

Fwiw, I was looking at brave.http.HttpRuleSampler and wondered should that be reused for secondary sampling as well.

**Comment by narayaruna** [comment]
If unifying rule evaluation on a http request/grpc call to make sampling decision for b3 or provisioning the `sampling_key` for secondary sampling is a long shot, allowing such evaluation in the secondary sampler for now will be useful.

For example, hooks in the [extract method](https://github.com/openzipkin-contrib/zipkin-secondary-sampling/blob/master/brave/src/main/java/brave/secondary_sampling/SecondarySamplingExtractor.java#L40) to match a rule and run a sampler to provision the `sampling_key` will be helpful.

To workaround this, a servlet filter/grpc interceptor is what I am using to provision the `sampling_key`. Here is a grpc interceptor example:

```
    public <ReqT, RespT> ServerCall.Listener<ReqT> interceptCall(
            ServerCall<ReqT, RespT> call,
            Metadata requestHeaders,
            ServerCallHandler<ReqT, RespT> next
    ) {
        .....
        // apply the rules and run the sampler. If there is a match and the sampler decision is true
        // then provision the `sampling_key` 
        String samplingKey = ....
        requestHeaders.put(SAMPLING, samplingKey);

        return next.startCall(call, requestHeaders);
    }

```

**Why is this relevant?**
This is useful to provision the `sampling_key` not just in the `gateway` service but in any service downstream. For example, an `auth` service downstream can provision the `sampling_key` to start tracing 50% of calls to the `doAuth` method and the next hop by setting `ttl=2`.

**Comment by narayaruna** [comment]
But more I think about this, the [extract method](https://github.com/openzipkin-contrib/zipkin-secondary-sampling/blob/master/brave/src/main/java/brave/secondary_sampling/SecondarySamplingExtractor.java#L40) might not be the right place to provision the `sampling_key`.

Probably doing this in the filter or interceptor is the right approach until there is a uniform way to start b3 sampling or secondary sampling by running the rules and samplers.

**Comment by adriancole** [comment]
upstream change is https://github.com/openzipkin/brave/pull/994. next step is to integrate it in this repo, which should make use case more easy to see.

**Comment by adriancole** [comment]
PS I moved the meat of the comment https://github.com/openzipkin-contrib/zipkin-secondary-sampling/issues/8#issuecomment-535312688 above to #10 as it is a separate concern: Provisioning is different than evaluation and the apis must be decoupled because of that.

**Comment by adriancole** [comment]
This shows how http can integrate https://github.com/openzipkin-contrib/zipkin-secondary-sampling/pull/18

**Comment by adriancole** [comment]
http sampler integration is now merged. I will raise a PR for a consolidated sampler in the test directory and proceed to RPC sampling.

**Comment by adriancole** [comment]
https://github.com/openzipkin-contrib/zipkin-secondary-sampling/pull/19 PTAL

personally very tired as worked all weekend on this. Not sure how much more time I can do in the next few days.

**Comment by narayaruna** [comment]
> #19 PTAL
> 
> personally very tired as worked all weekend on this. Not sure how much more time I can do in the next few days.

@adriancole no rush to land this. I have my interceptor and filter workaround for my immediate experiment.
