### ISSUE TITLE
About using Rps in a Trigger to control participation

### ISSUE THREAD

**Issue by narayaruna** [openzipkin-contrib/zipkin-secondary-sampling#9]
Have a question about a [unit test](https://github.com/openzipkin-contrib/zipkin-secondary-sampling/blob/master/brave/src/test/java/brave/secondary_sampling/integration/SecondarySamplingIntegratedTest.java).

The trigger is setup for `gatewaySampler` as follows:

```
TestSecondarySampler gatewayplaySampler = new TestSecondarySampler()
    .addTrigger("gatewayplay", "gateway", new Trigger().rps(50))
    .addTrigger("gatewayplay", "playback", new Trigger());
```

In this [test](https://github.com/openzipkin-contrib/zipkin-secondary-sampling/blob/master/brave/src/test/java/brave/secondary_sampling/integration/SecondarySamplingIntegratedTest.java#L173), **note** that the `sampling_key` is [provisioned](https://github.com/openzipkin-contrib/zipkin-secondary-sampling/blob/master/brave/src/test/java/brave/secondary_sampling/integration/SecondarySamplingIntegratedTest.java#L178) for **all** requests.

Because of `rps` rate limiting in `gateway`, the requests will be sampled at the rate of 50/sec. However, all requests will be sampled in `playback`.

This ^^ demonstrates the use case:
```
Sample `gateway` requests at 50/sec and sample all requests for `playback`.
```

However the use case for Netflix is the following:

```
Sample requests at 50/sec and `gateway` and `playback` should participate.
```

**Is there any issue in the sampler implementation itself?**
No. The **SecondarySampler** exposes the perfect API to plugin the necessary logic which is enough for Netflix.

**Then what is the issue?**
No issue really. Just that this unit test covers a different use case. That's all.

**Are there any relevance of this to any future work?**
Yes. This [issue](https://github.com/openzipkin-contrib/zipkin-secondary-sampling/issues/8) is related.

The secondary sampling key should be provisioned if the rule matches the request and the `rps` sampler picks this request for sampling. And then the `ttl` or `dynamic config` can control participation.

**Comment by adriancole** [comment]
Please use https://github.com/openzipkin-contrib/zipkin-secondary-sampling/issues/10 for things about provisioning in general so people don't have to read every issue and pull request comment in case there's a mention of provisioning.

The test glitch is could be least a limitation of the current apis available, or it could be a bug in the dummy trigger policy thing. I'll take a look at it

**Comment by adriancole** [comment]
You are right. In a prior design, we had a signal to pass downstream if upstream made a decision. This was how rate limiting based on a happens-before can work.

https://github.com/openzipkin/brave/blob/13f1230cbb4a8dbdba4c85b4c8a36561583e3912/brave/src/test/java/brave/features/propagation/SecondarySamplingTest.java#L77

I will raise that again.. basically it got lost in translation and needs to be both in the test and the design.

**Comment by adriancole** [comment]
https://github.com/openzipkin-contrib/zipkin-secondary-sampling/pull/14 fixes this
